@baseUrl = http://localhost:5000/api
@transactionId = 68fb8c1b546d152a8e03dad2

### Get all transactions
GET {{baseUrl}}/transactions
Accept: application/json

### Get single transaction
GET {{baseUrl}}/transactions/{{transactionId}}
Accept: application/json

### Create new transaction
POST {{baseUrl}}/transactions
Content-Type: application/json

{
  "date": "2015-9-24",
  "description": "ASEC W-wa Ratusz Ar/Warszawa",
  "amount": 1.70,
  "currency": "PLN",
  "category": "transport",
  "transactionType": "expense",
  "paymentMethod": "card",
  "account": "mBank"
}

### Update a transaction (PUT)
PUT {{baseUrl}}/transactions/{{transactionId}}
Content-Type: application/json

{ 
  "date": "2015-9-24",
  "description": "ASEC W-wa Ratusz Ar/Warszawa some change",
  "amount": 1.70,
  "currency": "PLN",
  "category": "transport",
  "transactionType": "expense",
  "paymentMethod": "card",
  "account": "mBank"
}

### Partial update of transaction (PATCH)
PATCH {{baseUrl}}/transactions/{{transactionId}}
Content-Type: application/json

{
  "date": "2015-24-9",
  "description1": "ASEC W-wa Ratusz Ar/Warszawa another change",
  "amount": -6
}

### Delete a transaction
DELETE {{baseUrl}}/transactions/68fbd9a408881cb90e2fbc54