@baseUrl = http://localhost:5000/api
@newUserId = i
@accessToken = i

# GET ALL USERS
GET {{baseUrl}}/users


### CREATE NEW USER
# @name createUser
POST {{baseUrl}}/users
Content-Type: application/json

{
  "firstName": "Woj",
  "lastName": "Zie",
  "email": "w@z.pl",
  "password": "123"
}


### LOGIN
# @name loginReq
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "w@z.pl",
  "password": "123"
}

# {
#   "email": "kurczak@ziemniak.pl",
#   "password": "dzik1234"
# }


### GET USER BY ACCESS TOKEN
@accessToken = {{loginReq.response.body.accessToken}}

GET {{baseUrl}}/auth/me
Authorization: Bearer {{accessToken}}


### REFRESH ACCESS TOKEN
GET {{baseUrl}}/auth/refresh
Cookie: refreshToken=fa5b75d8-09df-4473-b2f2-f51b28bec563.mi4o38we


### LOGOUT
@accessToken={{loginReq.response.body.accessToken}}
@refreshToken=8f56d041-b541-437d-907a-0f07bac79e52.mi3gijg9

POST {{baseUrl}}/auth/logout
Authorization: Bearer {{accessToken}}
Cookie: refreshToken=be667747-2361-41ee-924c-56d04ca4e2ca.mi4o4pkl


### GET USER BY ID
@newUserId = {{createUser.response.body.id}}
@accessToken = {{loginReq.response.body.accessToken}}

GET {{baseUrl}}/users/691f1e90b1e751ec54cb352b
# {{newUserId}}
Authorization: Bearer {{accessToken}}

### Delete new user by id

@newUserId = {{createUser.response.body.id}}

# 6956eda1c618f569aefc7dee - delete user with this id - wrong email
# 6956ef1de1e1c28869b6d0ba - correct test user with 1000 transactions (test1)
# 6956f021e1e1c28869b6d4b2 - correct test user with 20000 transactions (test2)
# 6957a68f17ad7b3dc76fa550 - there are also transfer transactions (test4)

DELETE {{baseUrl}}/users/{{newUserId}}

### CREATE TEST USER WITH RANDOM TRANSACTIONS

POST {{baseUrl}}/users/test
Content-Type: application/json

{
  "username": "test6",
  "totalTransactions": 20000
}

### DELETE ALL USERS
# !!! BE CAREFUL !!!

# DELETE {{baseUrl}}/users