@baseUrl = http://localhost:5000/api
@transactionId = 692071ec942967c3272e9682
@newTransactionId = i
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTU4MjE1YzQyMGZlMzdiZTllZTQyNWQiLCJlbWFpbCI6InRlc3QxQHRlc3QuY29tIiwiaWF0IjoxNzY5NDQ5Mjg1LCJleHAiOjE3Njk0NTEwODV9.J9DEJqHuvlS9shY2FKTInuZyTVsXbQMScvr0OfB0C1o

@wzTransactionId = 6922f287242096bfdbb168a3

@amount = minAmount=100.01&maxAmount=500
@PLN = currency=PLN
@EUR = currency=EUR
@CZK = currency=CZK
@category = category=food
@exchange = category=exchange
# when format of `endDate` is f.e. `2023/10/30` then it is actually transformed for filters
# to `2023-12-29T23:00:00` so 'less or equal' actually behaves as 'less'
# when format of `endDate` is f.e. `2023-10-30` then it is transformed for filters
# to `2023-12-30T00:00:00` so `less or equal` behaves as expected
@date = startDate=2022-11-17&endDate=2023-10-30
@date2 = startDate=2016-01-01&endDate=2017-01-01
@sorting = sortBy=date&sortOrder=asc
@pagination = limit=100&page=1
@type = transactionType=expense

### Get transactions with pagination, filters and sorting

GET {{baseUrl}}/transactions?{{exchange}}&{{sorting}}&{{pagination}}
Accept: application/json
Authorization: Bearer {{accessToken}}

### GET STATISTICS ABOUT TRANSACTIONS
@excludeCategories = excludeCategories=myAccount,investments
@yearAndMonth = year=2023

GET {{baseUrl}}/transactions/statistics?{{PLN}}&{{type}}&{{yearAndMonth}}&{{excludeCategories}}
Accept: application/json
Authorization: Bearer {{accessToken}}

### GET TOTALS FOR TRANSACTIONS
GET {{baseUrl}}/transactions/totals?{{excludeCategories}}&startDate=2024-12-01&endDate=2024-12-31
Accept: application/json
Authorization: Bearer {{accessToken}}

### EXPORT TRANSACTIONS AS CSV STREAM

# code commented as it returns all transactions in CSV format,
# so there is a lot of them and thus VSC gets clogged
# GET {{baseUrl}}/transactions/export
# Authorization: Bearer {{accessToken}}


### Get all transactions (still default pagination is applied)
GET {{baseUrl}}/transactions?startDate=2026-01-01
Accept: application/json
Authorization: Bearer {{accessToken}}

# income -  6972b1e2b479aa46a8af5209
# expense - 6972b1e2b479aa46a8af5207

### Get single transaction
GET {{baseUrl}}/transactions/6974d150efa585c6eca912e7
Accept: application/json

# 6976262aceeb9078893d8a43 - standard
# 6974d150efa585c6eca912e7 - exchange
# 6976263cceeb9078893d8a51 - transfer

### Create new standard transaction

# @name createTransaction
POST {{baseUrl}}/transactions/standard
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "date": "2026-01-24",
  "description": "VERY NEW TRANSACTION",
  "amount": 1.70,
  "currency": "PLN",
  "category": "transport",
  "transactionType": "expense",
  "paymentMethod": "card",
  "account": "mBank"
}

### CREATE NEW EXCHANGE TRANSACTIONS
POST {{baseUrl}}/transactions/exchange
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "date": "2026-01-24",
  "additionalDescription": "some additional desc",  
  "amountExpense": 20,
  "amountIncome": 84.23,
  "currencyExpense": "EUR",
  "currencyIncome": "PLN",
  "account": "revolut",
  "paymentMethod": "bankTransfer"
}

### CREATE NEW TRANSFER TRANSACTIONS
POST {{baseUrl}}/transactions/transfer
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "date": "2026-01-24",
  "additionalDescription": "z oszczędnościowego na zwykłe",  
  "amount": 12345.67,
  "currency": "PLN",
  "accountExpense": "mBank",
  "accountIncome": "aliorBank",
  "paymentMethod": "bankTransfer"
}

### Update STANDARD transaction
PUT {{baseUrl}}/transactions/standard/6976262aceeb9078893d8a43
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{ 
  "date": "2026-12-25",
  "description": "expense - food - 372.5971177941268 EUR - 2025-12-24",
  "amount": 372.5971177941268,
  "currency": "EUR",
  "category": "food",
  "transactionType": "expense",
  "paymentMethod": "card",
  "account": "creditAgricole"
}

### Update TRANSFER transaction
PUT {{baseUrl}}/transactions/transfer/6976263cceeb9078893d8a51
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{ 
  "date": "2015-9-24",
  "additionalDescription": "abcdef",
  "amount": 1.70,
  "currency": "PLN",
  "paymentMethod": "card",
  "accountExpense": "mBank",
  "accountIncome": "veloBank"
}

### Update EXCHAGE transaction
PUT {{baseUrl}}/transactions/exchange/6974d150efa585c6eca912e7
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "date": "2026-12-18",
  "additionalDescription": "123 some additional desc",
  "amountExpense": 200,
  "amountIncome": 840.23,
  "currencyExpense": "HUF",
  "currencyIncome": "RON",
  "account": "mBank",
  "paymentMethod": "bankTransfer"
}


### Delete a transaction

@newTransactionId = {{createTransaction.response.body.id}}

DELETE {{baseUrl}}/transactions/6974d150efa585c6eca912e7
Authorization: Bearer {{accessToken}}


### DELETE ALL TRANSACTIONS
# !!! BE CAREFUL !!!

# DELETE {{baseUrl}}/transactions
