
### LOGIN
# @name loginReq
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "test1@test.com",
  "password": "123"
}

###

@baseUrl = http://localhost:5000/api/transactions
@transactionId = 692071ec942967c3272e9682
@newTransactionId = i
@accessToken = {{loginReq.response.body.accessToken}}

@wzTransactionId = 6922f287242096bfdbb168a3

@amount = minAmount=100.01&maxAmount=500
@PLN = currency=PLN
@EUR = currency=EUR
@CZK = currency=CZK
@category = category=food
@exchange = category=exchange
# when format of `endDate` is f.e. `2023/10/30` then it is actually transformed for filters
# to `2023-12-29T23:00:00` so 'less or equal' actually behaves as 'less'
# when format of `endDate` is f.e. `2023-10-30` then it is transformed for filters
# to `2023-12-30T00:00:00` so `less or equal` behaves as expected
@date = startDate=2022-11-17&endDate=2023-10-30
@date2 = startDate=2016-01-01&endDate=2017-01-01
@sorting = sortBy=date&sortOrder=asc
@pagination = limit=100&page=1
@type = transactionType=expense

#--------------------------------------------------------------------------------------
#--------------------------------------------------------------------------------------

### Get transactions with pagination, filters and sorting
GET {{baseUrl}}?{{sorting}}&{{pagination}}&startDate=2026-02-04
Accept: application/json
Authorization: Bearer {{accessToken}}

#--------------------------------------------------------------------------------------
#--------------------------------------------------------------------------------------

### GET STATISTICS ABOUT TRANSACTIONS
@excludeCategories = excludeCategories=myAccount,investments
@yearAndMonth = year=2023

GET {{baseUrl}}/statistics?{{PLN}}&{{type}}&{{yearAndMonth}}&{{excludeCategories}}
Accept: application/json
Authorization: Bearer {{accessToken}}

#--------------------------------------------------------------------------------------
#--------------------------------------------------------------------------------------

### GET TOTALS FOR TRANSACTIONS
GET {{baseUrl}}/totals?{{excludeCategories}}&startDate=2024-12-01&endDate=2024-12-31
Accept: application/json
Authorization: Bearer {{accessToken}}

#--------------------------------------------------------------------------------------
#--------------------------------------------------------------------------------------

### EXPORT TRANSACTIONS AS CSV STREAM
# code commented as it returns all transactions in CSV format,
# so there is a lot of them and thus VSC gets clogged
# GET {{baseUrl}}/export
# Authorization: Bearer {{accessToken}}

#--------------------------------------------------------------------------------------
#--------------------------------------------------------------------------------------

### Get all transactions (still default pagination is applied)
GET {{baseUrl}}
Accept: application/json
Authorization: Bearer {{accessToken}}

# income -  6972b1e2b479aa46a8af5209
# expense - 6972b1e2b479aa46a8af5207

#--------------------------------------------------------------------------------------
#--------------------------------------------------------------------------------------

### Get single transaction
GET {{baseUrl}}/69830f15269a841a876428f0
Accept: application/json
Authorization: Bearer {{accessToken}}

# 6976262aceeb9078893d8a43 - standard
# 6974d150efa585c6eca912e7 - exchange
# 6976263cceeb9078893d8a51 - transfer

#--------------------------------------------------------------------------------------
#--------------------------------------------------------------------------------------

### Create new standard transaction

# "categoryId": "69812ea8e6de6ef869bfba38", (food)
# "category": "transport",
# "categoryId": "6980aef7f9f1739803300ef5", (exchange - system category)


# @name createTransaction
POST {{baseUrl}}/standard
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "date": "2026-02-04",
  "description": "VERY NEW TRANSACTION",
  "amount": 1.70,
  "currency": "PLN",
  "categoryId": "69812ea8e6de6ef869bfba38",
  "transactionType": "expense",
  "paymentMethod": "card",
  "account": "mBank"
}

#--------------------------------------------------------------------------------------
#--------------------------------------------------------------------------------------

### CREATE NEW EXCHANGE TRANSACTIONS
POST {{baseUrl}}/exchange
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "date": "2026-02-04",
  "additionalDescription": "some additional desc",  
  "amountExpense": 20,
  "amountIncome": 84.23,
  "currencyExpense": "EUR",
  "currencyIncome": "PLN",
  "account": "revolut",
  "paymentMethod": "bankTransfer"
}

#--------------------------------------------------------------------------------------
#--------------------------------------------------------------------------------------

### CREATE NEW TRANSFER TRANSACTIONS
POST {{baseUrl}}/transfer
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "date": "2026-02-04",
  "additionalDescription": "z oszczędnościowego na zwykłe",  
  "amount": 12345.67,
  "currency": "PLN",
  "accountExpense": "mBank",
  "accountIncome": "aliorBank",
  "paymentMethod": "bankTransfer"
}

#--------------------------------------------------------------------------------------
#--------------------------------------------------------------------------------------

# "category": "food",
# "categoryId": "69830737a0d0fb8f48f900cc" (transport)

### Update STANDARD transaction
PUT {{baseUrl}}/standard/69830f15269a841a876428f0
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{ 
  "date": "2026-12-25",
  "description": "expense - food - 372.5971177941268 EUR - 2025-12-24",
  "amount": 372.5971177941268,
  "currency": "EUR",
  "categoryId": "69830737a0d0fb8f48f900cc",
  "transactionType": "expense",
  "paymentMethod": "card",
  "account": "creditAgricole"
}

#--------------------------------------------------------------------------------------
#--------------------------------------------------------------------------------------

### Update TRANSFER transaction
PUT {{baseUrl}}/transfer/69830b42269a841a876428ba
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{ 
  "date": "2015-9-24",
  "additionalDescription": "abcdef",
  "amount": 1.70,
  "currency": "PLN",
  "paymentMethod": "card",
  "accountExpense": "mBank",
  "accountIncome": "veloBank"
}

#--------------------------------------------------------------------------------------
#--------------------------------------------------------------------------------------

### Update EXCHAGE transaction
PUT {{baseUrl}}/exchange/69830b9a269a841a876428d5
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "date": "2026-12-18",
  "additionalDescription": "123 some additional desc",
  "amountExpense": 200,
  "amountIncome": 840.23,
  "currencyExpense": "HUF",
  "currencyIncome": "RON",
  "account": "mBank",
  "paymentMethod": "bankTransfer"
}

#--------------------------------------------------------------------------------------
#--------------------------------------------------------------------------------------

### Delete a transaction
DELETE {{baseUrl}}/6974d150efa585c6eca912e7
Authorization: Bearer {{accessToken}}

#--------------------------------------------------------------------------------------
#--------------------------------------------------------------------------------------

### DELETE ALL TRANSACTIONS (of an authenticated user)
# !!! BE CAREFUL !!!
# DELETE {{baseUrl}}
# Authorization: Bearer {{accessToken}}

#--------------------------------------------------------------------------------------
#--------------------------------------------------------------------------------------

### CREATE TEST TRANSACTIONS (only when user has no transactions)
POST {{baseUrl}}/test
Authorization: Bearer {{accessToken}}

#--------------------------------------------------------------------------------------
#--------------------------------------------------------------------------------------