@baseUrl = http://localhost:5000/api/categories
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTU4MjE1YzQyMGZlMzdiZTllZTQyNWQiLCJlbWFpbCI6InRlc3QxQHRlc3QuY29tIiwiaWF0IjoxNzcwMTM4ODU3LCJleHAiOjE3NzAxNDA2NTd9.CXiKB6ZHajCQMecIfwlqOAmN3QMWV3mtHVw9hTQAstM

#--------------------------------------------------------------------------------------
#--------------------------------------------------------------------------------------

### GET ALL CATEGORIES

GET {{baseUrl}}
Accept: application/json
Authorization: Bearer {{accessToken}}

#--------------------------------------------------------------------------------------
#--------------------------------------------------------------------------------------

### GET CATEGORY BY ID

GET {{baseUrl}}/69812ea8e6de6ef869bfba38
Accept: application/json
Authorization: Bearer {{accessToken}}

#--------------------------------------------------------------------------------------
#--------------------------------------------------------------------------------------

### CREATE NEW CATEGORY

POST {{baseUrl}}
Accept: application/json
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "food"
}

#--------------------------------------------------------------------------------------
#--------------------------------------------------------------------------------------

### UPDATE CATEGORY

PUT {{baseUrl}}/69812ea8e6de6ef869bfba38
Accept: application/json
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "Food"
}

#--------------------------------------------------------------------------------------
#--------------------------------------------------------------------------------------

###
