@baseUrl = http://localhost:5000/api
@transactionId = 692071ec942967c3272e9682
@newTransactionId = i
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTIxOTI1ODNlOTY0MDdlYmUxYWMxY2EiLCJlbWFpbCI6IndAei5wbCIsImlhdCI6MTc2Njg0ODcwOSwiZXhwIjoxNzY2ODUyMzA5fQ.LmgwAg2lz9sItpEHFxv3VjGlUsPwPncdmtucEESXBeo

@wzTransactionId = 6922f287242096bfdbb168a3

@amount = minAmount=100.01&maxAmount=500
@PLN = currency=PLN
@EUR = currency=EUR
@CZK = currency=CZK
@category = category=food
@exchange = category=exchange
# when format of `endDate` is f.e. `2023/10/30` then it is actually transformed for filters
# to `2023-12-29T23:00:00` so 'less or equal' actually behaves as 'less'
# when format of `endDate` is f.e. `2023-10-30` then it is transformed for filters
# to `2023-12-30T00:00:00` so `less or equal` behaves as expected
@date = startDate=2022-11-17&endDate=2023-10-30
@date2 = startDate=2016-01-01&endDate=2017-01-01
@sorting = sortBy=date&sortOrder=asc
@pagination = limit=100&page=1
@type = transactionType=expense

### Get transactions with pagination, filters and sorting

GET {{baseUrl}}/transactions?{{exchange}}&{{sorting}}&{{pagination}}
Accept: application/json
Authorization: Bearer {{accessToken}}

### GET STATISTICS ABOUT TRANSACTIONS
@omitCategory = omitCategory=myAccount&omitCategory=investments
@yearAndMonth = year=2023

GET {{baseUrl}}/transactions/statistics?{{type}}&{{PLN}}&{{yearAndMonth}}&{{omitCategory}}
Accept: application/json
Authorization: Bearer {{accessToken}}

### GET TOTALS FOR TRANSACTIONS
GET {{baseUrl}}/transactions/totals?{{omitCategory}}&startDate=2024-12-01&endDate=2024-12-31
Accept: application/json
Authorization: Bearer {{accessToken}}

### EXPORT TRANSACTIONS AS CSV STREAM

# code commented as it returns all transactions in CSV format,
# so there is a lot of them and thus VSC gets clogged
# GET {{baseUrl}}/transactions/export
# Authorization: Bearer {{accessToken}}


### Get all transactions (still default pagination is applied)
GET {{baseUrl}}/transactions
Accept: application/json
Authorization: Bearer {{accessToken}}

### Get single transaction
GET {{baseUrl}}/transactions/{{transactionId}}
Accept: application/json

### Create new standard transaction

# @name createTransaction
POST {{baseUrl}}/transactions
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "date": "2025-12-16",
  "description": "VERY NEW TRANSACTION",
  "amount": 1.70,
  "currency": "PLN",
  "category": "transport",
  "transactionType": "expense",
  "paymentMethod": "card",
  "account": "mBank",
}

### CREATE NEW EXCHANGE TRANSACTIONS
POST {{baseUrl}}/transactions/exchange
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "date": "2025-12-17",
  "additionalDescription": "some additional desc",  
  "amountExpense": 20,
  "amountIncome": 84.23,
  "currencyExpense": "EUR",
  "currencyIncome": "PLN",
  "account": "revolut",
  "paymentMethod": "bankTransfer"
}

### CREATE NEW TRANSFER TRANSACTIONS
POST {{baseUrl}}/transactions/transfer
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "date": "2025-12-27",
  "additionalDescription": "z oszczędnościowego na zwykłe",  
  "amount": 12345.67,
  "currency": "PLN",
  "accountFrom": "mBank",
  "accountTo": "aliorBank",
  "paymentMethod": "bankTransfer"
}

### Update a transaction (PUT)
PUT {{baseUrl}}/transactions/{{wzTransactionId}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{ 
  "date": "2015-9-24",
  "description": "ASEC W-wa Ratusz Ar/Warszawa some change",
  "amount": 1.70,
  "currency": "PLN",
  "category": "transport",
  "transactionType": "expense",
  "paymentMethod": "card",
  "account": "mBank"
}

### Partial update of transaction (PATCH)
PATCH {{baseUrl}}/transactions/{{wzTransactionId}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "description": "tratata",
  "amount": 7.77
}

### Delete a transaction

@newTransactionId = {{createTransaction.response.body.id}}

DELETE {{baseUrl}}/transactions/694331f209d01dec2f8e0a07
Authorization: Bearer {{accessToken}}


### DELETE ALL TRANSACTIONS
# !!! BE CAREFUL !!!

DELETE {{baseUrl}}/transactions
