@baseUrl = http://localhost:5000/api/categories
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTU4MjE1YzQyMGZlMzdiZTllZTQyNWQiLCJlbWFpbCI6InRlc3QxQHRlc3QuY29tIiwiaWF0IjoxNzcwMDcyNTM1LCJleHAiOjE3NzAwNzQzMzV9.Wpo5Hhe8aC9hnCSgoPVI4KWd7H0nUz7seZEQA0RFyYo

#--------------------------------------------------------------------------------------
#--------------------------------------------------------------------------------------

### GET ALL CATEGORIES

GET {{baseUrl}}
Accept: application/json
Authorization: Bearer {{accessToken}}

#--------------------------------------------------------------------------------------
#--------------------------------------------------------------------------------------

### GET CATEGORY BY ID

GET {{baseUrl}}/6980aef7f9f1739803300ef5
Accept: application/json
Authorization: Bearer {{accessToken}}

#--------------------------------------------------------------------------------------
#--------------------------------------------------------------------------------------

### CREATE NEW CATEGORY

POST {{baseUrl}}
Accept: application/json
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "food"
}
