@baseUrl = http://localhost:5000/api

### LOGIN
# @name loginReq
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "test1@test.com",
  "password": "123"
}

###
@accessToken = {{loginReq.response.body.accessToken}}

#--------------------------------------------------------------------------------------
#--------------------------------------------------------------------------------------

### GET ALL USERS
GET {{baseUrl}}/users

#--------------------------------------------------------------------------------------
#--------------------------------------------------------------------------------------

### CREATE NEW USER
# @name createUser
POST {{baseUrl}}/users
Content-Type: application/json

{
  "firstName": "Abc",
  "lastName": "Def",
  "email": "g@h.ij",
  "password": "klm"
}

#--------------------------------------------------------------------------------------
#--------------------------------------------------------------------------------------

### GET USER BY ACCESS TOKEN
GET {{baseUrl}}/auth/me
Authorization: Bearer {{accessToken}}

#--------------------------------------------------------------------------------------
#--------------------------------------------------------------------------------------

### REFRESH ACCESS TOKEN
GET {{baseUrl}}/auth/refresh

#--------------------------------------------------------------------------------------
#--------------------------------------------------------------------------------------

### LOGOUT

POST {{baseUrl}}/auth/logout
Authorization: Bearer {{accessToken}}

#--------------------------------------------------------------------------------------
#--------------------------------------------------------------------------------------

### GET USER BY ID
@newUserId = {{createUser.response.body.id}}

GET {{baseUrl}}/users/6958215c420fe37be9ee425d
# {{newUserId}}
Authorization: Bearer {{accessToken}}

#--------------------------------------------------------------------------------------
#--------------------------------------------------------------------------------------

### Delete user by id
@newUserId = {{createUser.response.body.id}}
DELETE {{baseUrl}}/users/{{newUserId}}
Authorization: Bearer {{accessToken}}

#--------------------------------------------------------------------------------------
#--------------------------------------------------------------------------------------

### CREATE TEST USER WITH RANDOM TRANSACTIONS

POST {{baseUrl}}/users/test
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "username": "test1",
  "totalTransactions": 20000
}

#--------------------------------------------------------------------------------------
#--------------------------------------------------------------------------------------
